### ISSUE TITLE
Propor mockup para nova arquitetura de informação da página "Global research on coronavirus disease (COVID-19)"

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/wordpress-themes#44]
Propor nova arquitetura para a página

https://www.who.int/emergencies/diseases/novel-coronavirus-2019/global-research-on-novel-coronavirus-2019-ncov/

De maneira a manter o acesso às informações atualmente disponíveis, incluir a caixa de busca da interface WHO COVID, ter uma área para divulgar novidades (por exemplo: integração de preprints, ensaios clinicos etc) e uma área para destacar temas relacionados a COVID que remetem o usuário a estratégias de busca.

Utilizar a página https://www.who.int/emergencies/diseases/novel-coronavirus-2019 como base na construção desta nova arquitetura, para manter alinhamento com a identidade visual do site da OMS, assim como estilo de arquitetura.

**Comment by renatomurasaki** [comment]
@marcioalvessilva obrigado pelo mockup - http://mockups.teste.bireme.org/pagecovid/

Observações antes de enviar para a equipe da OMS:

### 1) Botão News/Update/Help
![image](https://user-images.githubusercontent.com/1226218/109339755-dd40fe00-7846-11eb-853e-62c626e12560.png)
- Creio que seria melhor retirá-lo da barra onde está a caixa de busca. Entendo que poderia colocar o botão News/Udapte/Help como um card em outra parte da página.
- Creio que para esta página podemos retirar o comboBox Title, Abstract, Subject

### 2) Disposição dos cards
![image](https://user-images.githubusercontent.com/1226218/109349854-56dfe880-7855-11eb-8a83-cccc36dd9f8a.png)

- Separei os cards em 3 grupos com cores diferentes. Cada cor é uma seção diferente, ou seja, estes cards não deveriam estar juntos na mesma seção. Cada seção estaria separada por um título
- Os cards no grupo vermelho vão para a seção de "Explore the database by subject" 
- Os cards no grupo verde vão para a seção "Clinical trials"
- Os cards no grupo azul vão para a seção "Other resources"

### Seção Informed Indicators
- Trocar o nome para Database Indicators

### Caixas "WHO is bringing..." e "Global researc ..."
- Colocá-las depois da caixa de busca

### Caixa de Disclaimer
- Deixá-la no final

### Criar as seguintes seções, baseando-se em integração via RSS, igual temos no GIM
- Latest journal articles
- Latest preprints
- Latest clinical trial registers

### Ordem das seções depois das caixas "WHO is bringing..." e "Global researc ..."
1) "Explore the database by subject"
2) Latest (RSS)
3) Database indicators
4) "Clinical trials"
5) "Other resources"
6) Disclaimer

**Comment by marcioalvessilva** [comment]
Bom dia Renato! Tudo em ordem com você, Santi e Carol? espero que estejam bem!
O mockup foi atualizado, mantive a identidade e redistribui o conteúdo conforme sua orientação, qualquer coisa me avise!

Boa semana amigo!
________________________________
De: Renato Murasaki <notifications@github.com>
Enviado: sexta-feira, 26 de fevereiro de 2021 17:27
Para: bireme/wordpress-themes <wordpress-themes@noreply.github.com>
Cc: Márcio Alves <marcioalvessilvajc@gmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [bireme/wordpress-themes] Propor mockup para nova arquitetura de informação da página "Global research on coronavirus disease (COVID-19)" (#44)


@marcioalvessilva<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarcioalvessilva&data=04%7C01%7Cdasilvmar%40paho.org%7C110b1367d44a49b16a1808d8da94fa91%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637499680705236808%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oJeO7m8zJkV0VX%2FqWxzS5IBD16Z6YgzHXfcHP2bxlPg%3D&reserved=0> obrigado pelo mockup - http://mockups.teste.bireme.org/pagecovid/<https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fmockups.teste.bireme.org%2Fpagecovid%2F&data=04%7C01%7Cdasilvmar%40paho.org%7C110b1367d44a49b16a1808d8da94fa91%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637499680705236808%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=u613ZwG77%2F0qBA2Fw2xUwodFMtTMFJhVkRCCnihxdMw%3D&reserved=0>

Observações antes de enviar para a equipe da OMS:

1) Botão News/Update/Help

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1226218%2F109339755-dd40fe00-7846-11eb-853e-62c626e12560.png&data=04%7C01%7Cdasilvmar%40paho.org%7C110b1367d44a49b16a1808d8da94fa91%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637499680705246808%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1JNbM65NVfqhb0Y0%2FlsosekjROpG%2FoCdTUzR7CKEqr8%3D&reserved=0>

  *   Creio que seria melhor retirá-lo da barra onde está a caixa de busca. Entendo que poderia colocar o botão News/Udapte/Help como um card em outra parte da página.
  *   Creio que para esta página podemos retirar o comboBox Title, Abstract, Subject

2) Disposição dos cards

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1226218%2F109349854-56dfe880-7855-11eb-8a83-cccc36dd9f8a.png&data=04%7C01%7Cdasilvmar%40paho.org%7C110b1367d44a49b16a1808d8da94fa91%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637499680705246808%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XwqwaDNXaulkiA9gbcYXpJcUjvKYej2oBMkCxT8f5Do%3D&reserved=0>

  *   Separei os cards em 3 grupos com cores diferentes. Cada cor é uma seção diferente, ou seja, estes cards não deveriam estar juntos na mesma seção. Cada seção estaria separada por um título
  *   Os cards no grupo vermelho vão para a seção de "Explore the database by subject"
  *   Os cards no grupo verde vão para a seção "Clinical trials"
  *   Os cards no grupo azul vão para a seção "Other resources"

Seção Informed Indicators

  *   Trocar o nome para Database Indicators

Caixas "WHO is bringing..." e "Global researc ..."

  *   Colocá-las depois da caixa de busca

Caixa de Disclaimer

  *   Deixá-la no final

Criar as seguintes seções, baseando-se em integração via RSS, igual temos no GIM

  *   Latest journal articles
  *   Latest preprints
  *   Latest clinical trial registers

Ordem das seções depois das caixas "WHO is bringing..." e "Global researc ..."

  1.  "Explore the database by subject"
  2.  Latest (RSS)
  3.  Database indicators
  4.  "Clinical trials"
  5.  "Other resources"
  6.  Disclaimer

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fwordpress-themes%2Fissues%2F44%23issuecomment-786876735&data=04%7C01%7Cdasilvmar%40paho.org%7C110b1367d44a49b16a1808d8da94fa91%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637499680705256800%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8pTvkTPs54Xd%2F9VZEO6OkdB8GEtiEV6nIaaE6mgFjGQ%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALTXRKCIR4PH3SJEH2WLNSDTA774BANCNFSM4YBF6ITQ&data=04%7C01%7Cdasilvmar%40paho.org%7C110b1367d44a49b16a1808d8da94fa91%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637499680705266796%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PasmPpBzP3oy5TcolWCGgsNvxnY9VZ%2Fkj5URUkx25rg%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by renatomurasaki** [comment]
@marcioalvessilva obrigado! Na minha opinião está ótimo para iniciar a discussão com a equipe da OMS. Há apenas um ajuste para fazer: Os cards da seção Clinical Trials estão trocados com a seção Explore the database by subject. Pode ajustar, por favor? OBrigado

**Comment by marcioalvessilva** [comment]
@renatomurasaki atualizado!

**Comment by marcioalvessilva** [comment]
Finalizado!
