### ISSUE TITLE
Habilitar idioma Francês e carregar textos para Portal Evid@Easy 

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/wordpress-themes#96]
Marcio,

Favor habilitar idioma francês e carregar os blocos de textos encaminhados pela @pintoros no documento abaixo.

[Traduçao Frances corrigida - Pagina Evid-Easy.docx](https://github.com/bireme/wordpress-themes/files/8035586/Traducao.Frances.corrigida.-.Pagina.Evid-Easy.docx)

**Comment by marcioalvessilva** [comment]
Bom dia, @pintoros , @viniciusandrade!
Por favor fazer a tradução do texto que aparecem no carrossel.

Aguardo!

**Comment by pintoros** [comment]
Marcio, você tem os originais para eu editar em cima? Tenho que trocar as imagens também.
Obrigada



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:7c4f6608-1a0e-4bbe-9737-69cfc2d396b4]

________________________________
De: Márcio Alves ***@***.***>
Enviado: quinta-feira, 10 de fevereiro de 2022 07:41
Para: bireme/wordpress-themes ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/wordpress-themes] Habilitar idioma Francês e carregar textos para Portal ***@***.*** (Issue #96)


Bom dia, @pintoros<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpintoros&data=04%7C01%7Cpintoros%40paho.org%7C12f26fbec335420fc77208d9ec81eb99%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637800865020874096%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=l%2FLyDyDsikhFTyLATIjYSlXaVM6zGy5z15%2F%2BRdA%2Fhik%3D&reserved=0> , @viniciusandrade<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fviniciusandrade&data=04%7C01%7Cpintoros%40paho.org%7C12f26fbec335420fc77208d9ec81eb99%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637800865020874096%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=x7ugy6OLXCQEOfGRQ%2F1EnI7qwosaoVVRQTAV6vTtWSs%3D&reserved=0>!
Por favor fazer a tradução do texto que aparecem no carrossel.

Aguardo!

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fwordpress-themes%2Fissues%2F96%23issuecomment-1034762334&data=04%7C01%7Cpintoros%40paho.org%7C12f26fbec335420fc77208d9ec81eb99%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637800865020874096%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Yr2OMM60zS%2BlI%2BLBswe%2Fo8IRA8EQqHJYcCJ9wQ2XY%2FE%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4HH4Z6O3IPMWPTQJ6TU2OI6HANCNFSM5N6NMNFA&data=04%7C01%7Cpintoros%40paho.org%7C12f26fbec335420fc77208d9ec81eb99%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637800865020874096%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=K2cOrxFnbnp3wyDyGG55Bj0RVZoOgv0HF%2F0PdvEJKak%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpintoros%40paho.org%7C12f26fbec335420fc77208d9ec81eb99%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637800865020874096%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jyOihxdD4RwhYJ%2FgqS1fUoxMTEwp6FC732OU9iIc7aE%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpintoros%40paho.org%7C12f26fbec335420fc77208d9ec81eb99%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637800865020874096%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6z9bsHvnc3FdeRc%2BQKq%2FkEcn1LbCidgKhJe8rfNSbt0%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by marcioalvessilva** [comment]
@pintoros , boa tarde!
Segue textos:


Passo 1 – Apresenta diferentes contextos em saúde, por exemplo, Doenças Negligenciadas
Passo 2 – Apresenta tópicos em saúde da acordo com o contexto escolhido, por exemplo:
Malária é um dos tópicos no contexto de Doenças ne
gligenciadas
Passo 3 – Agora indique o objetivo da sua pesquisa, no exemplo,  Evidências sobre as considerações para 
a implementação das opções ou  recomendações consideradas
Passo 4 – Os filtros por tipos de estudo são apresentados de acordo com o objetivo da sua pesquisa,
no exemplo optamos por Evidências de avaliações econômicas
As opções escolhidas levarão aos estudos disponíveis na BVS

Aguardo tradução

**Comment by pintoros** [comment]
@marcioalvessilva segue a tradução e algumas correções na interface, abaixo.
 
Tradução:
Étape 1 - Présente différents contextes de la santé, par exemple, les Maladies Négligées
Étape 2 – Présente les thèmes de santé selon le contexte choisi, par exemple: Le paludisme est l'un des sujets dans le contexte des Maladies Négligées
Étape 3 - Indiquez maintenant le but de votre recherche, dans l'exemple "Évidences sur les considérations relatives à la mise en œuvre des options ou des recommandations envisagées"
Étape 4 – Les filtres par types d'études sont présentés selon l'objet de votre recherche, dans l'exemple, nous avons choisi: "Évidence sur des évaluations économiques". Les options choisies conduiront aux études disponibles dans la BVS.

Interface:
1) Maladies Négligées não está traduzido (está em inglês) no primeiro quadro de navegação em francês.
2) Substituir na tradução da interface os termos Preuve e Preuves por Évidence ou Évidences.

Obrigada

**Comment by marcioalvessilva** [comment]
Boa tarde Rose!
1 - Cadastrei os banners e solicitei a Lilian ajuda para traduzir o logo
![image](https://user-images.githubusercontent.com/48724136/153662831-b9ac5a36-4425-4ab2-871f-b62c5e18b7cb.png)

2 - Fiz algumas atualizações no tema e abri chamado para alinhar teste com a produção
3 - Esse itens de interface que vc listou na resposta acima eu não encontrei, pode por favor me enviar um print

Aguardo!

**Comment by pintoros** [comment]
Segue o print @marcioalvessilva 

1) o primeiro tema de busca faltou traduzir
![image](https://user-images.githubusercontent.com/29313904/153665404-a13fa24d-d50a-4350-8bf2-728c18f5e3d8.png)
2) Nessas 2 áreas, a palavra preuve e preuves aparece várias vezes e em duas opções aparece o termo "données probantes" que também pode ser substituído por évidences.
![image](https://user-images.githubusercontent.com/29313904/153666861-151c6ee8-7167-438a-b257-7c43d296fc47.png)
![image](https://user-images.githubusercontent.com/29313904/153667493-f01270e3-45f5-4e00-9d62-8c02f9f42836.png)
Obrigada

**Comment by marcioalvessilva** [comment]
Entendi, @pintoros essa parte não é feita no site, @viniciusandrade você consegue ajustar? depois eu vou pegar os prints para montar os banners.

**Comment by pintoros** [comment]
Obrigada Márcio.



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:3ecb703c-0526-4b42-91b8-892bbe3431fd]

________________________________
De: Márcio Alves ***@***.***>
Enviado: sexta-feira, 11 de fevereiro de 2022 18:10
Para: bireme/wordpress-themes ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/wordpress-themes] Habilitar idioma Francês e carregar textos para Portal ***@***.*** (Issue #96)


Entendi, @pintoros<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpintoros&data=04%7C01%7Cpintoros%40paho.org%7C28cb07d37bac4885391608d9eda2fac4%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637802106526755768%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PFfb74l42WLaJazxBbRlz8khfBGJqaqlbTQf27sMLzs%3D&reserved=0> essa parte não é feita no site, @viniciusandrade<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fviniciusandrade&data=04%7C01%7Cpintoros%40paho.org%7C28cb07d37bac4885391608d9eda2fac4%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637802106526755768%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FQ97DdWaDapoG%2F8F5pyqtleSK7stnTNLoycz9StDMxQ%3D&reserved=0> você consegue ajustar? depois eu vou pegar os prints para montar os banners.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fwordpress-themes%2Fissues%2F96%23issuecomment-1036625825&data=04%7C01%7Cpintoros%40paho.org%7C28cb07d37bac4885391608d9eda2fac4%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637802106526755768%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=e5Demt7%2BPJVKZY0sM9zOpmc14N0RBUEh9xctd2SnCiE%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4G5OMTS446OIEQJCGDU2V3NTANCNFSM5N6NMNFA&data=04%7C01%7Cpintoros%40paho.org%7C28cb07d37bac4885391608d9eda2fac4%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637802106526755768%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rdyCJbaPVGOplWSKxzj%2BEBk%2Bx7M6kLCZg7N7ke%2BCRcw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpintoros%40paho.org%7C28cb07d37bac4885391608d9eda2fac4%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637802106526755768%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=019cF3M%2FMuCp059%2BRFh8OaUSmFfPH93RnKcVQaULLNc%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpintoros%40paho.org%7C28cb07d37bac4885391608d9eda2fac4%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637802106526755768%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=U559JQcy1Vvu0EIdA%2BTVaFh%2BaPTFh7KGPyHywp0%2F%2Bvo%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by viniciusandrade** [comment]
@pintoros atualizado a tradução para o item 1.

Os textos do item 2 estão de acordo com o documento enviado por email e aprovados pelo Ludovic e não consegui entender quais seriam os ajustes necessários.

Sugiro adicionar o documento na mesma área do Sharingponint (Cooperação Técnica > Projetos > Regional > Evid@Easy) com track changes habilitado e fazer as alterações para que eu possa ajustar no sistema.

Favor avisar quando disponível.

Obrigado

**Comment by viniciusandrade** [comment]
@pintoros  OK, ficaremos no aguardo dos textos revisado.

Obrigado

**Comment by pintoros** [comment]
Favor observar o chamado referente a tradução dos labels de navegação em: https://github.com/bireme/iahx-opac/issues/306

**Comment by pintoros** [comment]
Olá @marcioalvessilva , 
Eu devo algum conteúdo para a página em francês em https://bvsalud.org/evideasy?

Revisei o chamado e vi que a ultima demanda foi o texto das imagens que enviei em 11/fev.
As correções discutidas com @viniciusandrade foram solicitadas no https://github.com/bireme/iahx-opac/issues/306
Obrigada

**Comment by marcioalvessilva** [comment]
Olá @pintoros vou verificar com o @viniciusandrade porque para habilitar eu preciso de prints para sessão de banner.
Aguardo essa informação. abraço!

**Comment by pintoros** [comment]
Se for os prints da interface, Passos de 1 a 4, eu posso te enviar.


Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:1cfce3ad-4218-401f-8808-4c0777cc498e]

________________________________
De: Márcio Alves ***@***.***>
Enviado: quinta-feira, 25 de agosto de 2022 09:36
Para: bireme/wordpress-themes ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/wordpress-themes] Habilitar idioma Francês e carregar textos para Portal ***@***.*** (Issue #96)


Olá @pintoros<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpintoros&data=05%7C01%7Cpintoros%40paho.org%7C8282a7147b15464b110d08da8696634c%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637970277711209981%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FoY6rZUh4yNkVxdhgKcwQSLsoSf3kC87DY4BN1%2FWIeg%3D&reserved=0> vou verificar com o @viniciusandrade<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fviniciusandrade&data=05%7C01%7Cpintoros%40paho.org%7C8282a7147b15464b110d08da8696634c%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637970277711209981%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yoWIBdRVL%2Fv%2F09gRRC8bzMKldm%2BWvflsovLsJ6a5PaI%3D&reserved=0> porque para habilitar eu preciso de prints para sessão de banner.
Aguardo essa informação. abraço!

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fwordpress-themes%2Fissues%2F96%23issuecomment-1227199615&data=05%7C01%7Cpintoros%40paho.org%7C8282a7147b15464b110d08da8696634c%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637970277711209981%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YpvIo3e0md3o2u82S9ZhGJ1lAop0FDcB%2BJsAMuRbSIA%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4HTNQGWB6ZWET2RQXTV25SDTANCNFSM5N6NMNFA&data=05%7C01%7Cpintoros%40paho.org%7C8282a7147b15464b110d08da8696634c%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637970277711209981%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yb2drHUt%2FwdDB6F4AG9qsTdEwUxXbM3lOHhHIiQQ6qg%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by marcioalvessilva** [comment]
Por favor, se os labels estiverem correto fico no aguardo!

**Comment by pintoros** [comment]
Segue a captura  de imagens referente aos passos do carrossel:

![passo1_fr](https://user-images.githubusercontent.com/29313904/186673540-3ad30125-7695-4ab6-b9a7-0c9acefb7c13.JPG)
![passo2_fr](https://user-images.githubusercontent.com/29313904/186673581-a34cf069-5761-4dd2-9917-be70c0458545.JPG)
![passo3_fr](https://user-images.githubusercontent.com/29313904/186673618-2173e08d-7df2-4965-92cc-b4f420729e59.JPG)
![passo4_fr](https://user-images.githubusercontent.com/29313904/186673654-fc
![tela5_fr](https://user-images.githubusercontent.com/29313904/186673670-f3270a4b-f975-4513-a70d-81363f29fb61.JPG)
5942f4-118e-4b37-85ad-8d821e5a58fc.JPG)

link para ultima imagem, caso necessite capturar novamente: https://pesquisa.bvsalud.org/portal/?lang=fr&fb=&q=&skfp=true&range_year_start=&range_year_end=&filter%5Btag_contexto%5D%5B%5D=3_ND&filter%5Btag_tema_saude%5D%5B%5D=3_malaria&filter%5Btype_of_study%5D%5B%5D=health_economic_evaluation#step-1

**Comment by pintoros** [comment]
Marcio, para a página,  por favor usar a versão que está no link da abertura desse chamado. Obrigada

**Comment by marcioalvessilva** [comment]
Por favor validar!

**Comment by pintoros** [comment]
Em qual url posso validar? 
O link está disponível no menu de navegação por idioma na produção, mas o conteúdo não aparece
Obrigada

**Comment by marcioalvessilva** [comment]
https://bvsalud.org/evideasy/fr/

**Comment by pintoros** [comment]
Marcio, no carrossel a tela 4 e a tela 5 do carrossel precisam de correção na frase.

A frase da tela 4 é: Les filtres par types d'études sont présentés selon l'objet de votre recherche, dans l'exemple, nous avons choisi: "Évidence sur des évaluations économiques". 

A frase da tela 5 é: Les options choisies conduiront aux études disponibles dans la BVS.

**Comment by marcioalvessilva** [comment]
Atualizado!

Passo 4
![image](https://user-images.githubusercontent.com/48724136/188269942-7ccd5820-d4a8-46af-82f9-ab8a752e0c88.png)
Passso 5
![image](https://user-images.githubusercontent.com/48724136/188269973-0900240f-1d1b-4ebd-ac24-0333379658b2.png)

**Comment by marcioalvessilva** [comment]
Olá @pintoros !
Por favor me enviar os textos do banner em espanhol, identifiquei que estão errados.

**Comment by pintoros** [comment]
Márcio, não identifiquei na interface texto errado em espanhol. Poderia sinalizar onde?

Obrigada

**Comment by pintoros** [comment]
Frases do banner em es para correção:

Paso 2 – Presenta los temas de salud de acuerdo al contexto elegido, por ejemplo: Malaria es uno de los temas en el contexto de Enfermedades Desatendidas

Las opciones elegidas darán lugar a los estudios disponibles en la BVS.

**Comment by marcioalvessilva** [comment]
Atualizados!

**Comment by marcioalvessilva** [comment]
Finalizado!
